name: build-test-deploy

on: push

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build

  test-job:
    needs: build-job
    runs-on: ubuntu-latest

    steps:
      - name: check out repo fro testing
        uses: actions/checkout@v4
      - name: install node js for testing
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run test

  deploy-job:
    needs: test-job

    permissions:
      contents: write
      pages: write
      id-token: write

    environment: 
     name: production
     url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo for deployment
        uses: actions/checkout@v4
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup node for deplyment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: configure github pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - run: npm install 
      - run: npm run build
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
        
    
    


    
