name: build-test-deploy

on: push

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build

  test-job:
    needs: build-job
    runs-on: ubuntu-latest

    steps:
      - name: check out repo fro testing
        uses: actions/checkout@v4
      - name: install node js for testing
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run test
    
